export ZSH="/home/thomas/.oh-my-zsh"

alias vim="nvim"
alias cat="bat"
alias grep="rg"
alias xhd="cd /run/media/thomas"
alias cs-update="/home/thomas/repos/eolas/_scripts/auto_save.sh"
alias cs-query="/home/thomas/repos/eolas/_scripts/query.sh"

# Set properties based on OS

ZSH_THEME=""
plugins=(git npm fzf-tab zsh-autosuggestions zsh-syntax-highlighting)

# Search against /home/thomas/repos/computer_science


# User configuration

source ~/dotfiles/.env
source $ZSH/oh-my-zsh.sh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"


eval "$(starship init zsh)"
