export ZSH="/home/thomas/.oh-my-zsh"

alias vim="nvim"
alias cat="bat"
alias grep="rg" 
alias chrome="google-chrome-stable"
alias spot="ncspot"
alias xhd="cd /run/media/thomas"
alias cs-save="/home/thomas/repos/bash_scripts/automate_commit.sh"
alias cs-clean=""
alias cs-all=""
# Set properties based on OS

ZSH_THEME=spaceship
SPACESHIP_TIME_SHOW=false
SPACESHIP_PROMPT_ASYNC=true
SPACESHIP_CHAR_SYMBOL="▶ " 
#SPACESHIP_CHAR_SUFFIX="}"
plugins=(git npm zsh-autosuggestions zsh-syntax-highlighting)

# User configuration

source $ZSH/oh-my-zsh.sh



export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
